package com.lybia.cryptowallet

import com.lybia.cryptowallet.coinkits.CommonCoinsManager
import com.lybia.cryptowallet.wallets.cardano.CardanoAddress
import com.lybia.cryptowallet.wallets.cardano.CardanoAddressType
import io.kotest.property.Arb
import io.kotest.property.arbitrary.*
import io.kotest.property.checkAll
import kotlinx.coroutines.test.runTest
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Property-based tests for CoinsManager address type dispatch.
 */
class CoinsManagerPropertyTest {

    private val testMnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"

    private val manager = CommonCoinsManager(mnemonic = testMnemonic)

    /**
     * Generate a random valid Ed25519 public key (32 bytes) and chain code (32 bytes)
     * to produce a Byron address.
     */
    private fun arbByronAddress(): Arb<String> =
        Arb.byteArray(Arb.constant(32), Arb.byte()).flatMap { pubKey ->
            Arb.byteArray(Arb.constant(32), Arb.byte()).map { chainCode ->
                CardanoAddress.createByronAddress(pubKey, chainCode)
            }
        }

    /**
     * Generate a random valid Shelley base address from random key hashes (28 bytes each).
     */
    private fun arbShelleyBaseAddress(): Arb<String> =
        Arb.byteArray(Arb.constant(28), Arb.byte()).flatMap { paymentHash ->
            Arb.byteArray(Arb.constant(28), Arb.byte()).flatMap { stakingHash ->
                Arb.boolean().map { isTestnet ->
                    CardanoAddress.createBaseAddress(paymentHash, stakingHash, isTestnet)
                }
            }
        }

    /**
     * Generate a random valid Shelley enterprise address from random key hash (28 bytes).
     */
    private fun arbShelleyEnterpriseAddress(): Arb<String> =
        Arb.byteArray(Arb.constant(28), Arb.byte()).flatMap { paymentHash ->
            Arb.boolean().map { isTestnet ->
                CardanoAddress.createEnterpriseAddress(paymentHash, isTestnet)
            }
        }

    // Feature: cardano-midnight-support, Property 19: CoinsManager SendCoin Dispatches Correctly for Address Types
    // **Validates: Requirements 10.5**
    @Test
    fun sendCoinDispatchesCorrectlyForAddressTypes() = runTest {
        // Test Byron addresses → should dispatch to bootstrap witness
        checkAll(100, arbByronAddress()) { byronAddress ->
            val addressType = CardanoAddress.getAddressType(byronAddress)
            assertEquals(
                CardanoAddressType.BYRON,
                addressType,
                "Generated Byron address should be detected as BYRON"
            )
            val witnessType = manager.getWitnessTypeForAddress(byronAddress)
            assertEquals(
                "bootstrap",
                witnessType,
                "Byron address should use bootstrap witness"
            )
        }

        // Test Shelley base addresses → should dispatch to vkey witness
        checkAll(100, arbShelleyBaseAddress()) { shelleyAddress ->
            val addressType = CardanoAddress.getAddressType(shelleyAddress)
            assertEquals(
                CardanoAddressType.SHELLEY_BASE,
                addressType,
                "Generated Shelley base address should be detected as SHELLEY_BASE"
            )
            val witnessType = manager.getWitnessTypeForAddress(shelleyAddress)
            assertEquals(
                "vkey",
                witnessType,
                "Shelley address should use vkey witness"
            )
        }

        // Test Shelley enterprise addresses → should dispatch to vkey witness
        checkAll(100, arbShelleyEnterpriseAddress()) { enterpriseAddress ->
            val addressType = CardanoAddress.getAddressType(enterpriseAddress)
            assertEquals(
                CardanoAddressType.SHELLEY_ENTERPRISE,
                addressType,
                "Generated Shelley enterprise address should be detected as SHELLEY_ENTERPRISE"
            )
            val witnessType = manager.getWitnessTypeForAddress(enterpriseAddress)
            assertEquals(
                "vkey",
                witnessType,
                "Shelley enterprise address should use vkey witness"
            )
        }
    }
}
