package com.lybia.cryptowallet.cardano

import com.lybia.cryptowallet.wallets.cardano.CardanoAddress
import com.lybia.cryptowallet.wallets.cardano.CardanoAddressType
import io.kotest.property.Arb
import io.kotest.property.arbitrary.*
import io.kotest.property.checkAll
import kotlinx.coroutines.test.runTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Property-based tests for Cardano address generation and validation.
 */
class CardanoAddressPropertyTest {

    // ---- Generators ----

    /** Generate a random 32-byte array (Ed25519 public key size). */
    private fun arbBytes32(): Arb<ByteArray> =
        Arb.byteArray(Arb.constant(32), Arb.byte())

    /** Generate a random 28-byte array (Blake2b-224 hash size). */
    private fun arbBytes28(): Arb<ByteArray> =
        Arb.byteArray(Arb.constant(28), Arb.byte())

    /** Generate a random boolean for testnet flag. */
    private fun arbTestnet(): Arb<Boolean> = Arb.boolean()

    // ---- Property Tests ----

    // Feature: cardano-midnight-support, Property 3: Byron Address Generation and Validation Round-Trip
    // **Validates: Requirements 2.1, 2.2**
    @Test
    fun byronAddressRoundTrip() = runTest {
        checkAll(100, arbBytes32(), arbBytes32()) { publicKey, chainCode ->
            val address = CardanoAddress.createByronAddress(publicKey, chainCode)

            // Generated address should be non-empty
            assertTrue(address.isNotEmpty(), "Byron address should not be empty")

            // Generated address should be valid
            assertTrue(
                CardanoAddress.isValidByronAddress(address),
                "Generated Byron address should be valid: $address"
            )

            // Address type should be BYRON
            assertEquals(
                CardanoAddressType.BYRON,
                CardanoAddress.getAddressType(address),
                "Address type should be BYRON"
            )

            // Validation should return no error
            val error = CardanoAddress.validateByronAddress(address)
            assertEquals(null, error, "Validation error should be null for valid address")
        }
    }

    // Feature: cardano-midnight-support, Property 4: Invalid Byron Address Detection
    // **Validates: Requirements 2.4**
    @Test
    fun invalidByronAddressDetection() = runTest {
        checkAll(100, Arb.string(1..80, Codepoint.alphanumeric())) { randomStr ->
            // Random alphanumeric strings should almost never be valid Byron addresses
            // (the probability of a random string being a valid Base58+CBOR+CRC32 is negligible)
            if (!CardanoAddress.isValidByronAddress(randomStr)) {
                val error = CardanoAddress.validateByronAddress(randomStr)
                assertNotNull(error, "Invalid Byron address should have error description")
                assertTrue(error.isNotEmpty(), "Error description should not be empty")
            }
        }
    }

    // Also test truncated Byron addresses
    @Test
    fun invalidByronAddressTruncated() = runTest {
        checkAll(100, arbBytes32(), arbBytes32()) { publicKey, chainCode ->
            val validAddress = CardanoAddress.createByronAddress(publicKey, chainCode)
            // Truncate the address
            if (validAddress.length > 5) {
                val truncated = validAddress.substring(0, validAddress.length / 2)
                assertFalse(
                    CardanoAddress.isValidByronAddress(truncated),
                    "Truncated Byron address should be invalid"
                )
                val error = CardanoAddress.validateByronAddress(truncated)
                assertNotNull(error, "Truncated address should have error description")
            }
        }
    }

    // Feature: cardano-midnight-support, Property 5: Shelley Address Generation with Correct Bech32 Encoding
    // **Validates: Requirements 3.1, 3.2, 3.4**
    @Test
    fun shelleyAddressBech32Encoding() = runTest {
        checkAll(100, arbBytes28(), arbBytes28(), arbTestnet()) { paymentHash, stakingHash, isTestnet ->
            // Test base address
            val baseAddr = CardanoAddress.createBaseAddress(paymentHash, stakingHash, isTestnet)
            val expectedPrefix = if (isTestnet) "addr_test" else "addr"
            assertTrue(
                baseAddr.startsWith("${expectedPrefix}1"),
                "Base address should start with '${expectedPrefix}1', got: ${baseAddr.take(15)}"
            )

            // Test enterprise address
            val entAddr = CardanoAddress.createEnterpriseAddress(paymentHash, isTestnet)
            assertTrue(
                entAddr.startsWith("${expectedPrefix}1"),
                "Enterprise address should start with '${expectedPrefix}1'"
            )

            // Test reward address
            val rewardPrefix = if (isTestnet) "stake_test" else "stake"
            val rewardAddr = CardanoAddress.createRewardAddress(stakingHash, isTestnet)
            assertTrue(
                rewardAddr.startsWith("${rewardPrefix}1"),
                "Reward address should start with '${rewardPrefix}1'"
            )

            // Verify Bech32 decoding works (valid encoding)
            val (hrp, _) = com.lybia.cryptowallet.utils.Bech32.decode(baseAddr)
            assertEquals(expectedPrefix, hrp, "Decoded HRP should match expected prefix")

            // Verify header byte encodes correct type
            val baseData = com.lybia.cryptowallet.utils.Bech32.decode(baseAddr).second
            val basePayload = com.lybia.cryptowallet.utils.Bech32.convertBits(baseData, 5, 8, false)
            val baseHeader = basePayload[0].toInt() and 0xFF
            assertEquals(0x00 or (if (isTestnet) 0x00 else 0x01), baseHeader and 0xFF,
                "Base address header should encode type 0x00 and correct network")

            val entData = com.lybia.cryptowallet.utils.Bech32.decode(entAddr).second
            val entPayload = com.lybia.cryptowallet.utils.Bech32.convertBits(entData, 5, 8, false)
            val entHeader = entPayload[0].toInt() and 0xFF
            assertEquals(0x60 or (if (isTestnet) 0x00 else 0x01), entHeader and 0xFF,
                "Enterprise address header should encode type 0x60 and correct network")

            val rewData = com.lybia.cryptowallet.utils.Bech32.decode(rewardAddr).second
            val rewPayload = com.lybia.cryptowallet.utils.Bech32.convertBits(rewData, 5, 8, false)
            val rewHeader = rewPayload[0].toInt() and 0xFF
            assertEquals(0xE0 or (if (isTestnet) 0x00 else 0x01), rewHeader and 0xFF,
                "Reward address header should encode type 0xE0 and correct network")
        }
    }

    // Feature: cardano-midnight-support, Property 6: Shelley Address Generation and Validation Round-Trip
    // **Validates: Requirements 3.3**
    @Test
    fun shelleyAddressRoundTrip() = runTest {
        checkAll(100, arbBytes28(), arbBytes28(), arbTestnet()) { paymentHash, stakingHash, isTestnet ->
            // Base address round-trip
            val baseAddr = CardanoAddress.createBaseAddress(paymentHash, stakingHash, isTestnet)
            assertTrue(CardanoAddress.isValidShelleyAddress(baseAddr),
                "Generated base address should be valid: $baseAddr")
            assertEquals(CardanoAddressType.SHELLEY_BASE, CardanoAddress.getAddressType(baseAddr))

            // Enterprise address round-trip
            val entAddr = CardanoAddress.createEnterpriseAddress(paymentHash, isTestnet)
            assertTrue(CardanoAddress.isValidShelleyAddress(entAddr),
                "Generated enterprise address should be valid: $entAddr")
            assertEquals(CardanoAddressType.SHELLEY_ENTERPRISE, CardanoAddress.getAddressType(entAddr))

            // Reward address round-trip
            val rewardAddr = CardanoAddress.createRewardAddress(stakingHash, isTestnet)
            assertTrue(CardanoAddress.isValidShelleyAddress(rewardAddr),
                "Generated reward address should be valid: $rewardAddr")
            assertEquals(CardanoAddressType.SHELLEY_REWARD, CardanoAddress.getAddressType(rewardAddr))
        }
    }

    // Feature: cardano-midnight-support, Property 7: Invalid Shelley Address Detection
    // **Validates: Requirements 3.6**
    @Test
    fun invalidShelleyAddressDetection() = runTest {
        checkAll(100, Arb.string(1..80, Codepoint.alphanumeric())) { randomStr ->
            // Random strings should not be valid Shelley addresses
            if (!CardanoAddress.isValidShelleyAddress(randomStr)) {
                val error = CardanoAddress.validateShelleyAddress(randomStr)
                assertNotNull(error, "Invalid Shelley address should have error description")
                assertTrue(error.isNotEmpty(), "Error description should not be empty")
            }
        }
    }

    // Also test Shelley addresses with wrong prefix
    @Test
    fun invalidShelleyAddressWrongPrefix() = runTest {
        checkAll(100, arbBytes28(), arbBytes28()) { paymentHash, stakingHash ->
            val validAddr = CardanoAddress.createBaseAddress(paymentHash, stakingHash, false)
            // Replace prefix with invalid one
            val invalidAddr = "bc1" + validAddr.substringAfter("1")
            assertFalse(
                CardanoAddress.isValidShelleyAddress(invalidAddr),
                "Address with wrong prefix should be invalid"
            )
        }
    }

    // Test Shelley addresses with corrupted payload
    @Test
    fun invalidShelleyAddressCorruptedPayload() = runTest {
        checkAll(100, arbBytes28(), arbBytes28(), arbTestnet()) { paymentHash, stakingHash, isTestnet ->
            val validAddr = CardanoAddress.createBaseAddress(paymentHash, stakingHash, isTestnet)
            // Corrupt a character in the middle
            if (validAddr.length > 20) {
                val chars = validAddr.toCharArray()
                val idx = validAddr.length / 2
                chars[idx] = if (chars[idx] == 'q') 'p' else 'q'
                val corrupted = String(chars)
                // Corrupted address should fail validation (Bech32 checksum will fail)
                assertFalse(
                    CardanoAddress.isValidShelleyAddress(corrupted),
                    "Corrupted Shelley address should be invalid"
                )
            }
        }
    }
}
